# UPGMA Algorithm

1. Assign each taxon to its own cluster

2. Define one leaf for each taxon; place it at height 0

3. While more than two clusters:

    - Determine two clusters $i$ and $j$ with smallest $d_{ij}$
    
    - Define a new cluster $C_k = C_i ∪ C_j$

    - Define a node $k$ with children $i$ and $j$, place it at height $d_{ij}/2$
    
    - Replace clusters $i$ and $j$ with $k$
    
    - Compute distance between $k$ and other clusters
    
4. Join last two clusters $i$ and $j$ by root at height $d_{ij}/2$

In [1]:
import numpy as np

In [2]:
# Input matrices must be square and symmetric with -1s on the diagonal

example = [
    [-1, 19, 27, 8, 33, 18, 13],
    [19, -1, 31, 18, 36, 1, 13],
    [27, 31, -1, 26, 41, 32, 29],
    [8, 18, 26, -1, 31, 17, 14],
    [33, 36, 41, 31, -1, 35, 28],
    [18, 1, 32, 17, 35, -1, 12],
    [13, 13, 29, 14, 28, 12, -1]
]

In [ ]:
# example = {
#     0: [],
#     1: [19],
#     2: [27, 31],
#     3: [8, 18, 26],
#     4: [33, 36, 41, 31],
#     5: [18, 1, 32, 17, 35],
#     6: [13, 13, 29, 14, 28, 12]
# }

In [10]:
def upgma_iteration(matrix):

    # Convert matrix input to numpy array
    matrix = np.array(matrix, dtype=float)
    dim = matrix.shape

    # Check to make sure matrix size is valid for the algorithm
    assert(dim[0] == dim[1]), "Input is not a square matrix."
    assert(dim[0 != 1]), "Everything is grouped."

    # Find the shortest pairwise distance and the corresponding indices (groups)
    current_min = np.max(matrix)
    pair = (-1,-1)
    for r in range(dim[0]):
        for c in range(dim[1]):
            if r <= c:
                continue
            elif current_min > matrix[r,c]:
                current_min = matrix[r,c]
                pair = (r, c)

    # Calculate the depth of the new branch
    depth = current_min / 2

    # Get all values in the row corresponding to each item in pair
    lr = matrix[:, pair[0]]
    lc = matrix[:, pair[1]]

    # Calculate the mean pairwise distances with other sequences in new matrix.
    lrc_avg = (lr + lc) / 2

    # Remove the second occurence of -1
    print(pair)
    print(lr)
    print(lc)
    print(lrc_avg)
    print(np.where(lrc_avg==0))
    second_negative_index = np.where(lrc_avg==0)[0][1]
    lrc_avg = np.delete(lrc_avg, second_negative_index)

    # Construct the new matrix
    r = pair[0]
    c = pair[1]
    new_matrix = np.delete(matrix, r, axis=0)
    new_matrix = np.delete(new_matrix, r, axis=1)

    for i in range(len(lrc_avg)):
        new_matrix[c,i] = lrc_avg[i]
        new_matrix[i,c] = lrc_avg[i]
    
    return {"new_matrix":new_matrix, "pair":pair, "depth":depth}

In [11]:
def upgma_full(matrix):

    matrix = np.array(matrix, dtype=float)
    dim = matrix.shape[0]
    pairing_stack = []
    
    while dim > 1:
        print(matrix)
        print(dim)
        iterresults = upgma_iteration(matrix)
        pairing_stack.append(iterresults)
        matrix = iterresults["new_matrix"]
        dim = matrix.shape[0]


In [12]:
stack = upgma_full(example)

[[-1. 19. 27.  8. 33. 18. 13.]
 [19. -1. 31. 18. 36.  1. 13.]
 [27. 31. -1. 26. 41. 32. 29.]
 [ 8. 18. 26. -1. 31. 17. 14.]
 [33. 36. 41. 31. -1. 35. 28.]
 [18.  1. 32. 17. 35. -1. 12.]
 [13. 13. 29. 14. 28. 12. -1.]]
7
(5, 1)
[18.  1. 32. 17. 35. -1. 12.]
[19. -1. 31. 18. 36.  1. 13.]
[18.5  0.  31.5 17.5 35.5  0.  12.5]
(array([1, 5]),)
[[-1.  18.5 27.   8.  33.  13. ]
 [18.5  0.  31.5 17.5 35.5 12.5]
 [27.  31.5 -1.  26.  41.  29. ]
 [ 8.  17.5 26.  -1.  31.  14. ]
 [33.  35.5 41.  31.  -1.  28. ]
 [13.  12.5 29.  14.  28.  -1. ]]
6
(3, 0)
[ 8.  17.5 26.  -1.  31.  14. ]
[-1.  18.5 27.   8.  33.  13. ]
[ 3.5 18.  26.5  3.5 32.  13.5]
(array([], dtype=int64),)


IndexError: index 1 is out of bounds for axis 0 with size 0